Revert "audio: Make getPresentationPosition pure virtual"
This reverts commit 75678ad5002b0da3d4c40a861c95a7ed41338413.

Without this change, audio-legacy cannot compile and throws this error:
   hardware/qcom/audio-legacy/qsd8k/AudioHardware.cpp:245:45: error: cannot allocate an object of abstract type 'android_audio_legacy::AudioHardware::AudioStreamOutMSM72xx'
   out = new AudioStreamOutMSM72xx();

Thanks to fonz93: https://github.com/SlimLP-Y300/android_device_huawei_u8825/issues/1