Revert "audio: Make getPresentationPosition pure virtual"
This reverts commit 3ca773310ade547e540e878d748cd10e8e9f1282.

Without this change, audio-legacy cannot compile and throws this error:
   hardware/qcom/audio-legacy/qsd8k/AudioHardware.cpp:245:45: error: cannot allocate an object of abstract type 'android_audio_legacy::AudioHardware::AudioStreamOutMSM72xx'
   out = new AudioStreamOutMSM72xx();

Thanks to fonz93: https://github.com/SlimLP-Y300/android_device_huawei_u8825/issues/1

Change-Id: I11be7d4c74f9372e3470e9835c400182ea13297b